# 参考文档：https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # 插件唯一标识名（用于系统内部识别）
  name: qsl-management
spec:
  enabled: true
  version: 2.2.5
  requires: ">=2.23.0"
  author:
    name: bi1kbu
    website: https://github.com/bi1kbu
  logo: logo.png
  homepage: https://github.com/bi1kbu/qsl-management#readme
  repo: https://github.com/bi1kbu/qsl-management
  issues: https://github.com/bi1kbu/qsl-management/issues
  displayName: "业余无线电 QSL卡片管理系统"
  description: "业余无线电系列插件(1)：业余无线电QSL卡片管理系统，用于QSO记录、QSL收发卡、线上EYEBALL收发卡、线下EYEBALL收发卡等场景的全流程管理系统"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/bi1kbu/qsl-management/blob/main/LICENSE"
