export interface QslMenuModule {
  key: string
  title: string
  group: string
  priority: number
  viewPermission: string
  editPermission: string
  viewDependencies: string[]
  editDependencies: string[]
}

const pluginPermissionPrefix = 'plugin:qsl-management'

const toViewPermission = (key: string): string => `${pluginPermissionPrefix}:${key}:view`
const toEditPermission = (key: string): string => `${pluginPermissionPrefix}:${key}:edit`

const stationProfileViewPermission = toViewPermission('station-profile')
const stationProfileEditPermission = toEditPermission('station-profile')
const reportAuditlogViewPermission = toViewPermission('report-auditlog')
const reportAuditlogEditPermission = toEditPermission('report-auditlog')
const importExportViewPermission = toViewPermission('import-export')
const importExportEditPermission = toEditPermission('import-export')
const addressBureauViewPermission = toViewPermission('address-bureau')
const addressBureauEditPermission = toEditPermission('address-bureau')

export const qslMenuModules: QslMenuModule[] = [
  {
    key: 'overview-dashboard',
    title: '总览看板',
    group: '总览',
    priority: 10,
    viewPermission: toViewPermission('overview-dashboard'),
    editPermission: toEditPermission('overview-dashboard'),
    viewDependencies: [
      toViewPermission('qso-record'),
      toViewPermission('card-record'),
      toViewPermission('mail-send-confirm'),
      toViewPermission('mail-receive-confirm'),
    ],
    editDependencies: [toViewPermission('overview-dashboard')],
  },
  {
    key: 'system-settings',
    title: '系统参数',
    group: '配置',
    priority: 10,
    viewPermission: toViewPermission('system-settings'),
    editPermission: toEditPermission('system-settings'),
    viewDependencies: [],
    editDependencies: [toViewPermission('system-settings')],
  },
  {
    key: 'station-profile',
    title: '通信地址',
    group: '配置',
    priority: 20,
    viewPermission: stationProfileViewPermission,
    editPermission: stationProfileEditPermission,
    viewDependencies: [toViewPermission('equipment-catalog')],
    editDependencies: [stationProfileViewPermission, toViewPermission('equipment-catalog')],
  },
  {
    key: 'station-equipment',
    title: '本台设备',
    group: '配置',
    priority: 30,
    viewPermission: stationProfileViewPermission,
    editPermission: stationProfileEditPermission,
    viewDependencies: [toViewPermission('equipment-catalog')],
    editDependencies: [stationProfileViewPermission, toViewPermission('equipment-catalog')],
  },
  {
    key: 'station-card',
    title: '本台卡片',
    group: '配置',
    priority: 40,
    viewPermission: stationProfileViewPermission,
    editPermission: stationProfileEditPermission,
    viewDependencies: [toViewPermission('equipment-catalog')],
    editDependencies: [stationProfileViewPermission, toViewPermission('equipment-catalog')],
  },
  {
    key: 'qso-record',
    title: '通联日志',
    group: '通联业务',
    priority: 10,
    viewPermission: toViewPermission('qso-record'),
    editPermission: toEditPermission('qso-record'),
    viewDependencies: [toViewPermission('equipment-catalog'), stationProfileViewPermission],
    editDependencies: [toViewPermission('qso-record')],
  },
  {
    key: 'card-record',
    title: '创建卡片',
    group: '通联业务',
    priority: 20,
    viewPermission: toViewPermission('card-record'),
    editPermission: toEditPermission('card-record'),
    viewDependencies: [toViewPermission('qso-record'), stationProfileViewPermission],
    editDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
  },
  {
    key: 'card-issue',
    title: '制卡签发',
    group: '通联业务',
    priority: 40,
    viewPermission: toViewPermission('card-issue'),
    editPermission: toEditPermission('card-issue'),
    viewDependencies: [toViewPermission('card-record'), addressBureauViewPermission],
    editDependencies: [toViewPermission('card-issue'), toViewPermission('card-record'), addressBureauViewPermission],
  },
  {
    key: 'mail-send-confirm',
    title: '发信确认',
    group: '通联业务',
    priority: 50,
    viewPermission: toViewPermission('mail-send-confirm'),
    editPermission: toEditPermission('mail-send-confirm'),
    viewDependencies: [toViewPermission('card-record')],
    editDependencies: [toViewPermission('mail-send-confirm'), toViewPermission('card-record')],
  },
  {
    key: 'mail-receive-confirm',
    title: '送达确认',
    group: '通联业务',
    priority: 60,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'online-exchange-request-review',
    title: '换卡申请审核',
    group: '线上换卡业务',
    priority: 10,
    viewPermission: toViewPermission('exchange-request-review'),
    editPermission: toEditPermission('exchange-request-review'),
    viewDependencies: [addressBureauViewPermission, toViewPermission('card-record')],
    editDependencies: [toViewPermission('exchange-request-review'), toEditPermission('card-record')],
  },
  {
    key: 'online-card-record',
    title: '创建卡片',
    group: '线上换卡业务',
    priority: 20,
    viewPermission: toViewPermission('card-record'),
    editPermission: toEditPermission('card-record'),
    viewDependencies: [toViewPermission('qso-record'), stationProfileViewPermission],
    editDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
  },
  {
    key: 'online-card-issue',
    title: '制卡签发',
    group: '线上换卡业务',
    priority: 30,
    viewPermission: toViewPermission('card-issue'),
    editPermission: toEditPermission('card-issue'),
    viewDependencies: [toViewPermission('card-record'), addressBureauViewPermission],
    editDependencies: [toViewPermission('card-issue'), toViewPermission('card-record'), addressBureauViewPermission],
  },
  {
    key: 'online-mail-send-confirm',
    title: '发信确认',
    group: '线上换卡业务',
    priority: 40,
    viewPermission: toViewPermission('mail-send-confirm'),
    editPermission: toEditPermission('mail-send-confirm'),
    viewDependencies: [toViewPermission('card-record')],
    editDependencies: [toViewPermission('mail-send-confirm'), toViewPermission('card-record')],
  },
  {
    key: 'online-delivery-confirm',
    title: '送达确认',
    group: '线上换卡业务',
    priority: 50,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'offline-activity',
    title: '创建活动',
    group: '线下换卡业务',
    priority: 10,
    viewPermission: toViewPermission('exchange-request-review'),
    editPermission: toEditPermission('exchange-request-review'),
    viewDependencies: [toViewPermission('exchange-request-review')],
    editDependencies: [toViewPermission('exchange-request-review')],
  },
  {
    key: 'offline-card-record',
    title: '创建卡片',
    group: '线下换卡业务',
    priority: 20,
    viewPermission: toViewPermission('card-record'),
    editPermission: toEditPermission('card-record'),
    viewDependencies: [toViewPermission('qso-record'), stationProfileViewPermission],
    editDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
  },
  {
    key: 'offline-card-issue',
    title: '制卡签发',
    group: '线下换卡业务',
    priority: 30,
    viewPermission: toViewPermission('card-issue'),
    editPermission: toEditPermission('card-issue'),
    viewDependencies: [toViewPermission('card-record'), addressBureauViewPermission],
    editDependencies: [toViewPermission('card-issue'), toViewPermission('card-record'), addressBureauViewPermission],
  },
  {
    key: 'offline-delivery-confirm',
    title: '送达确认',
    group: '线下换卡业务',
    priority: 40,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'receive-qso',
    title: '通联收卡',
    group: '收卡业务',
    priority: 10,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'receive-online-eyeball',
    title: '线上换卡收卡',
    group: '收卡业务',
    priority: 20,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'receive-eyeball',
    title: '线下换卡收卡',
    group: '收卡业务',
    priority: 30,
    viewPermission: toViewPermission('mail-receive-confirm'),
    editPermission: toEditPermission('mail-receive-confirm'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record')],
    editDependencies: [
      toViewPermission('mail-receive-confirm'),
      toViewPermission('card-record'),
      toViewPermission('qso-record'),
    ],
  },
  {
    key: 'card-mutation',
    title: '卡片异动',
    group: '数据',
    priority: 5,
    viewPermission: toViewPermission('card-mutation'),
    editPermission: toEditPermission('card-mutation'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('qso-record'), addressBureauViewPermission],
    editDependencies: [
      toViewPermission('card-mutation'),
      toEditPermission('card-record'),
      toViewPermission('qso-record'),
      addressBureauViewPermission,
    ],
  },
  {
    key: 'qso-query',
    title: '通联记录查询',
    group: '审计',
    priority: 10,
    viewPermission: toViewPermission('qso-query'),
    editPermission: toEditPermission('qso-query'),
    viewDependencies: [toViewPermission('qso-record')],
    editDependencies: [toViewPermission('qso-query')],
  },
  {
    key: 'card-query',
    title: '卡片记录查询',
    group: '审计',
    priority: 20,
    viewPermission: toViewPermission('card-query'),
    editPermission: toEditPermission('card-query'),
    viewDependencies: [toViewPermission('card-record')],
    editDependencies: [toViewPermission('card-query')],
  },
  {
    key: 'receive-record-query',
    title: '收卡记录查询',
    group: '审计',
    priority: 25,
    viewPermission: toViewPermission('card-query'),
    editPermission: toEditPermission('card-query'),
    viewDependencies: [toViewPermission('card-record'), toViewPermission('mail-receive-confirm')],
    editDependencies: [toViewPermission('card-query')],
  },
  {
    key: 'report-auditlog',
    title: '统计报表',
    group: '审计',
    priority: 30,
    viewPermission: reportAuditlogViewPermission,
    editPermission: reportAuditlogEditPermission,
    viewDependencies: [
      toViewPermission('qso-query'),
      toViewPermission('card-query'),
      toViewPermission('exchange-request-review'),
      toViewPermission('mail-send-confirm'),
      toViewPermission('mail-receive-confirm'),
    ],
    editDependencies: [reportAuditlogViewPermission],
  },
  {
    key: 'audit-log',
    title: '审计日志',
    group: '审计',
    priority: 40,
    viewPermission: reportAuditlogViewPermission,
    editPermission: reportAuditlogEditPermission,
    viewDependencies: [
      toViewPermission('qso-query'),
      toViewPermission('card-query'),
      toViewPermission('exchange-request-review'),
      toViewPermission('mail-send-confirm'),
      toViewPermission('mail-receive-confirm'),
    ],
    editDependencies: [reportAuditlogViewPermission],
  },
  {
    key: 'address-management',
    title: '地址管理',
    group: '数据',
    priority: 10,
    viewPermission: addressBureauViewPermission,
    editPermission: addressBureauEditPermission,
    viewDependencies: [],
    editDependencies: [addressBureauViewPermission],
  },
  {
    key: 'bureau-management',
    title: '卡片局管理',
    group: '数据',
    priority: 20,
    viewPermission: addressBureauViewPermission,
    editPermission: addressBureauEditPermission,
    viewDependencies: [],
    editDependencies: [addressBureauViewPermission],
  },
  {
    key: 'equipment-catalog',
    title: '设备库维护',
    group: '数据',
    priority: 30,
    viewPermission: toViewPermission('equipment-catalog'),
    editPermission: toEditPermission('equipment-catalog'),
    viewDependencies: [],
    editDependencies: [toViewPermission('equipment-catalog')],
  },
  {
    key: 'import-export',
    title: '导入导出',
    group: '数据',
    priority: 40,
    viewPermission: importExportViewPermission,
    editPermission: importExportEditPermission,
    viewDependencies: [
      toViewPermission('qso-query'),
      toViewPermission('card-query'),
      toViewPermission('exchange-request-review'),
      addressBureauViewPermission,
      toViewPermission('equipment-catalog'),
    ],
    editDependencies: [
      importExportViewPermission,
      toEditPermission('qso-record'),
      toEditPermission('card-record'),
      toEditPermission('exchange-request-review'),
      addressBureauEditPermission,
      toEditPermission('equipment-catalog'),
    ],
  },
]
